apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-07-02T13:50:53Z"
  labels:
    app: mealie
  name: mealie
  namespace: mealie
  resourceVersion: "27203"
  uid: 1505a0c4-91ca-4e3d-baae-7a4bf5633efd
spec:
  clusterIP: 10.43.136.112
  clusterIPs:
  - 10.43.136.112
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
