apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-httpd-depl
  name: my-httpd-depl
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-httpd-depl
  template:
    metadata:
      labels:
        app: my-httpd-depl
    spec:
      containers:
      - image: httpd:alpine3.22
        name: httpd
  strategy:
    type: Recreate
